version: 1.0.{build}
image:
- Visual Studio 2019

configuration:
- Debug

environment:
  matrix:
    - generator: "Visual Studio 16 2019"
    - generator: "MinGW makefiles"

before_build:
- 'cmake -G %generator% .'

build:
  project: cut.sln
  verbosity: normal

test_script:
- 'cmake --build . --target check'