version: 1.0.{build}
image:
- Visual Studio 2019

configuration:
- Debug

before_build:
- 'cmake --version'
- 'cmake -G "Visual Studio 16 2019" .'

build:
  verbosity: normal

test_script:
- 'cmake --build . --target check'