version: 1.0.{build}
image:
- Visual Studio 2019

configuration:
- Debug

environment:
  matrix:
    - GENERATOR: Visual Studio 16 2019
    - GENERATOR: MinGW makefiles

init:
  - cmd: echo GENERATOR=%GENERATOR%

build_script:
  - cmd: md build
  - cmd: cd build
  - cmd: cmake .. -G %GENERATOR%
  - cmd: cmake --build .

test_script:
- cmd: cmake --build . --target check