version: 1.0.{build}
environment:
  matrix:
    - GENERATOR: "Visual Studio 16 2019"
    - GENERATOR: "MinGW Makefiles"

image:
- Visual Studio 2019

build_script:
  - cmd: md build
  - cmd: cd build
  - cmd: cmake .. -G "%GENERATOR%"
  - cmd: cmake --build .

test_script:
- cmd: cmake --build . --target check