version: 1.0.{build}
environment:
  matrix:
    # - generator: "Visual Studio 16 2019"
    #   platform: x64
    - generator: "MinGW Makefiles"
      platform: x32
      # platform: mingw64
    #  cxx_path: c:\msys64\mingw64\bin;c:\msys64\usr\bin

image:
- Visual Studio 2019

before_build:
- ps: |
    if ($env:cxx_path -ne "") {
      $env:path = "$env:cxx_path;$env:path"
    }
    & ls c:\

build_script:
- ps: |
    md build
    cd build
    & cmake .. -G "$env:generator"
    & cmake --build . --target check
